# Numerical Python

## NumPy

<a href="https://numpy.org/">
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" width="300px">
</a>

```python
import numpy as np
```

* Numpy provides fast numerical arrays
* Provides the `ndarray` type storing contiguous memory arrays for numeric types rather than as Python objects
* Computation with NumPy can be incredibly fast versus Python which stores numbers as individual objects
* Operators for `ndarray` implement a range of mathematical operations allowing vectorisation of computation

In [1]:
python_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
python_array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2]:
import numpy as np
numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
numpy_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Stored as a contiguous block of data in memory, each item is a value and not Python objects


Arrays have properties describing their shape and contents:

In [3]:
print(numpy_array)
print(type(numpy_array))     # type of Python object
print(numpy_array.size)      # total number of values
print(numpy_array.shape)     # array shape, i.e., size of each dimension
print(numpy_array.dtype)     # data type, all stored values have this type
print(numpy_array.ndim)      # number of dimensions, ie. len(numpy_array.shape)
print(numpy_array.itemsize)  # size of each data value in bytes
print(numpy_array.nbytes)    # size of whole array in bytes, ie. numpy_array.size*numpy_array.itemsize

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
9
(3, 3)
int64
2
8
72


Every array has a dtype defining the type of values stored
* Integer values (`np.int32`, `np.uint8`, etc.)
* Float values (`np.float32`, `np.float64`)
* Boolean values (`np.bool`)
* Complex values, structure types, strings, etc.

In [4]:
values = 0, 1.5, 2
print(np.array(values))
print(np.array(values, dtype=np.uint8))
print(np.array(values, dtype=bool))

[0.  1.5 2. ]
[0 1 2]
[False  True  True]


Various functions exist for creating arrays:

$I_4$

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [7]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [8]:
np.full((2, 2), 42)

array([[42, 42],
       [42, 42]])

In [9]:
np.random.rand(2, 2)

array([[0.79374532, 0.34705931],
       [0.13312487, 0.03230703]])

## Questions

Be careful with the data types:

In [10]:
array_ints = np.array((-1, 0, 1, 255))
print(array_ints.dtype)
print(array_ints)

int64
[ -1   0   1 255]


In [11]:
print(array_ints)
print(array_ints + 1)

[ -1   0   1 255]
[  0   1   2 256]


In [12]:
array_uints = array_ints.astype(np.uint8)
print(array_ints)
print(array_uints)

[ -1   0   1 255]
[255   0   1 255]


In [13]:
print(array_uints)
print(array_uints + 1)

[255   0   1 255]
[0 1 2 0]


In [14]:
np.array(-1, dtype=np.uint16)

array(65535, dtype=uint16)

In [15]:
np.array(65536, dtype=np.uint16)

array(0, dtype=uint16)

Be careful with floating-point arithmetic:

In [16]:
0.1

0.1

In [17]:
0.1 + 0.1

0.2

In [18]:
0.1 + 0.1 + 0.1

0.30000000000000004

In [19]:
3 * np.float32(0.1)

0.30000000447034836

In [20]:
3 * np.float64(0.1)

0.30000000000000004

In [21]:
3 * np.float128(0.1)

0.30000000000000001665

In [22]:
3 * np.float16(0.1)

0.2999267578125

https://0.30000000000000004.com/

Arrays can be _reshaped_:

In [23]:
arange = np.arange(12)
print(arange.shape)
arange

(12,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arange.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
arange.reshape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [26]:
arange.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

<img src="https://github.com/elegant-scipy/elegant-scipy/raw/master/figures/NumPy_ndarrays_v2.png" width="600px">

In [27]:
column = arange[:, np.newaxis]
print(column.shape)
column

(12, 1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [28]:
np.newaxis is None

True

In [29]:
row = column.T
print(row.shape)
row

(1, 12)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

Slicing arrays:

<img src="https://swcarpentry.github.io/python-novice-inflammation/fig/python-zero-index.svg" width="800px">

[From [software carpentry](https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html)]


In [30]:
print(numpy_array)
print(numpy_array[0, 1])
print(numpy_array[1, 0])
print(numpy_array[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
4
9


<img src="https://swcarpentry.github.io/python-novice-inflammation/fig/python-operations-across-axes.png" width="800px">

[From [software carpentry](https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html)]

In [31]:
print(numpy_array)
print(numpy_array.mean(axis=0))
print(numpy_array.mean(axis=1))
print(numpy_array.mean())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
[2. 5. 8.]
5.0


In [32]:
array = np.arange(60).reshape(3, 4, 5)
array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [33]:
array[:, :2, :].shape

(3, 2, 5)

In [34]:
array[:, :2].shape

(3, 2, 5)

In [35]:
array[..., :2].shape

(3, 4, 2)

In [36]:
array[..., 2].shape

(3, 4)

* When Numpy arrays are sliced, a view is returned
* This is a shallow copy of the original which uses the original allocated memory
* Changes to the view affect the original
* Deep copying can be done with the `copy` method

In [37]:
a = np.arange(10)
print(a)

b = a[3:6]
b[:] = 0  # assign 0 to every position in b

print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 0 0 0 6 7 8 9]


In [38]:
a = np.arange(10)
print(a)

b = a.copy()[3:6]
b[:] = 0  # assign 0 to every position in b

print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


* Operators are overloaded on arrays to implement vectorized mathematical operations
* Eg. `__add__` (`+`) implements element-wise addition, `-` is element-wise subtraction, etc.
* Boolean operators (`==`, `<=`, etc.) are element-wise and produce arrays of boolean values

In [39]:
a = np.random.rand(2, 2)
a

array([[0.0070714 , 0.11678851],
       [0.59434732, 0.32762322]])

In [40]:
mask = a > 0.5
mask

array([[False, False],
       [ True, False]])

In [41]:
a[mask]

array([0.59434732])

In [42]:
a + 10

array([[10.0070714 , 10.11678851],
       [10.59434732, 10.32762322]])

In [43]:
a + a

array([[0.0141428 , 0.23357702],
       [1.18869463, 0.65524643]])

* These implement per-element operations and produce new arrays
* Matrix operators also provided:

$A \cdot A$

In [44]:
a.dot(a)  # or a @ a, or np.dot(a, a)

array([[0.06946294, 0.03908849],
       [0.19892485, 0.17674991]])

$A^T$

In [45]:
a.T  # transpose

array([[0.0070714 , 0.59434732],
       [0.11678851, 0.32762322]])

* Assignment operators modify existing arrays rather than create new ones
* Represents another important efficiency concern, choose one method or the other depending on need

In [46]:
print(id(a))
b = a
print(id(b))

140216665953264
140216665953264


In [47]:
print(id(a))
print(id(b))
b = a.copy()
print(id(b))

140216665953264
140216665953264
140216665956048


In [48]:
print(id(a))
print(id(b))
b += a
print(id(b))

140216665953264
140216665956048
140216665956048


In [49]:
print(id(a))
print(id(b))
b = b + a
print(id(b))

140216665953264
140216665956048
140216665955280


## To know more

- [NumPy user guide](https://numpy.org/doc/stable/user/)

### To know _much_ more

- [NumPy Reference](https://numpy.org/doc/stable/reference/)
- [MyBinder - Elegant Scipy](https://mybinder.org/v2/gh/elegant-scipy/notebooks/master?filepath=index.ipynb) (interactive book!)

## Questions

[Some cells have been adapted from [Dr Eric Kerfoot's](https://kclpure.kcl.ac.uk/portal/eric.kerfoot.html)]