# Numerical Python

## Compiled vs. interpreted languages

### Compiled languages

Contents of a file `sum.c` containing C code:

```c
#include <stdio.h>

int main(void) {
  int a = 20;
  int b = 22;
  int c = a + b;
  printf("Result: %d\n", c);
  return 0;
}
```

```shell
$ gcc sum.c --output run_sum
$ ./run_sum
Result: 42
```

(Extra: [conversion to assembly during compilation](https://godbolt.org/z/qT9d6dTc6))

### Interpreted languages

Contents of a file `sum.py` containing Python code:

```python
a = 20
b = 22
c = a + b
print("Result:", c)
```


```shell
$ python run.py
Result: 42
```

## NumPy

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" width="300px">

```python
import numpy as np
```

* Numpy provides fast numerical arrays
* Provides the `ndarray` type storing contiguous memory arrays for numeric types rather than as Python objects
* Computation with NumPy can be incredibly fast versus Python which stores numbers as individual objects
* Operators for `ndarray` implement a range of mathematical operations allowing vectorisation of computation

In [1]:
python_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
python_array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2]:
import numpy as np
numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
numpy_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Stored as a contiguous block of data in memory, each item is a value and not Python objects


Arrays have properties describing their shape and contents:

In [3]:
print(type(numpy_array))     # type of Python object
print(numpy_array.size)      # total number of values
print(numpy_array.shape)     # array shape, i.e., size of each dimension
print(numpy_array.dtype)     # data type, all stored values have this type
print(numpy_array.ndim)      # number of dimensions, ie. len(numpy_array.shape)
print(numpy_array.itemsize)  # size of each data value in bytes
print(numpy_array.nbytes)    # size of whole array in bytes, ie. numpy_array.size*numpy_array.itemsize

<class 'numpy.ndarray'>
9
(3, 3)
int64
2
8
72


Every array has a dtype defining the type of values stored
* Integer values (`np.int32`, `np.uint8`, etc.)
* Float values (`np.float32`, `np.float64`)
* Boolean values (`np.bool`)
* Complex values, structure types, strings, etc.

In [4]:
values = 0, 1.5, 2
print(np.array(values))
print(np.array(values, dtype=np.uint8))
print(np.array(values, dtype=bool))

[0.  1.5 2. ]
[0 1 2]
[False  True  True]


Various functions exist for creating arrays:

$I_4$

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.full((2, 2), 42)

array([[42, 42],
       [42, 42]])

In [7]:
np.random.rand(2, 2)

array([[0.62261735, 0.66308777],
       [0.07700882, 0.96797068]])

In [8]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

Be careful with the data types:

In [10]:
array_ints = np.array((-1, 0, 1, 255))
print(array_ints.dtype)
print(array_ints)

int64
[ -1   0   1 255]


In [11]:
array_ints + 1

array([  0,   1,   2, 256])

In [12]:
array_uints = array_ints.astype(np.uint8)
array_uints

array([255,   0,   1, 255], dtype=uint8)

In [13]:
array_uints + 1

array([0, 1, 2, 0], dtype=uint8)

In [14]:
np.array(-1, dtype=np.uint16)

array(65535, dtype=uint16)

In [15]:
np.array(65536, dtype=np.uint16)

array(0, dtype=uint16)

Be careful with floating-point arithmetic:

In [16]:
0.1

0.1

In [17]:
0.1 + 0.1

0.2

In [18]:
0.1 + 0.1 + 0.1

0.30000000000000004

In [19]:
3 * np.float32(0.1)

0.30000000447034836

In [20]:
3 * np.float64(0.1)

0.30000000000000004

In [21]:
3 * np.float128(0.1)

0.30000000000000001665

In [22]:
3 * np.float16(0.1)

0.2999267578125

Arrays can be _reshaped_:

In [23]:
arange = np.arange(6)
print(arange.shape)
arange

(6,)


array([0, 1, 2, 3, 4, 5])

In [24]:
arange.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
arange.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
column = arange[:, np.newaxis]
print(column.shape)
column

(6, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [27]:
np.newaxis is None

True

In [28]:
row = column.T
print(row.shape)
row

(1, 6)


array([[0, 1, 2, 3, 4, 5]])

Slicing arrays:

<img src="https://swcarpentry.github.io/python-novice-inflammation/fig/python-zero-index.svg" width="800px">

[From [software carpentry](https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html)]


<img src="https://swcarpentry.github.io/python-novice-inflammation/fig/python-operations-across-axes.png" width="600px">

[From [software carpentry](https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html)]

In [29]:
array = np.arange(60).reshape(3, 4, 5)
array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [30]:
array[:, :2, :].shape

(3, 2, 5)

In [31]:
array[:, :2].shape

(3, 2, 5)

In [32]:
array[..., :2].shape

(3, 4, 2)

In [33]:
array[..., 2].shape

(3, 4)

* When Numpy arrays are sliced, a view is returned
* This is a shallow copy of the original which uses the original allocated memory
* Changes to the view affect the original
* Deep copying can be done with the `copy` method

In [34]:
a = np.arange(10)
print(a)

b = a[3:6]
b[:] = 0  # assign 0 to every position in b

print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 0 0 0 6 7 8 9]


In [35]:
a = np.arange(10)
print(a)

b = a.copy()[3:6]
b[:] = 0  # assign 0 to every position in b

print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


* Operators are overloaded on arrays to implement vectorized mathematical operations
* Eg. `__add__` (`+`) implements element-wise addition, `-` is element-wise subtraction, etc.
* Boolean operators (`==`, `<=`, etc.) are element-wise and produce arrays of boolean values

In [36]:
a = np.random.rand(3, 3)
a

array([[0.43419996, 0.52638646, 0.42580958],
       [0.96007586, 0.65844019, 0.05524108],
       [0.92894875, 0.70243366, 0.72710132]])

In [37]:
a + 10

array([[10.43419996, 10.52638646, 10.42580958],
       [10.96007586, 10.65844019, 10.05524108],
       [10.92894875, 10.70243366, 10.72710132]])

In [38]:
a + a

array([[0.86839992, 1.05277292, 0.85161916],
       [1.92015172, 1.31688038, 0.11048217],
       [1.8578975 , 1.40486733, 1.45420264]])

* These implement per-element operations and produce new arrays
* Matrix operators also provided:

$A \cdot A$

In [39]:
a.dot(a)  # or a @ a, or np.dot(a, a)

array([[1.08945581, 0.87425396, 0.52357137],
       [1.10033356, 0.97771761, 0.48534831],
       [1.75317897, 1.46223704, 0.9630348 ]])

$A^T$

In [40]:
a.T  # transpose

array([[0.43419996, 0.96007586, 0.92894875],
       [0.52638646, 0.65844019, 0.70243366],
       [0.42580958, 0.05524108, 0.72710132]])

* Assignment operators modify existing arrays rather than create new ones
* Represents another important efficiency concern, choose one method or the other depending on need

In [42]:
b = a.copy()
b += 10  # add to b, nothing new created
b *= a   # multiply, semantically equivalent to b=b*a but faster

* Many more operations are defined as methods of `array` or as library functions:

In [43]:
b = a.sum()  # sum of all values
b = a.min(axis=1)  # minimal values along axis 1
b = np.linalg.inv(a)  # matrix inverse

To know more: [NumPy user guide](https://numpy.org/doc/stable/user/)

To know _much_ more:
- [NumPy Reference](https://numpy.org/doc/stable/reference/)
- [MyBinder - Elegant Scipy](https://mybinder.org/v2/gh/elegant-scipy/notebooks/master?filepath=index.ipynb) (interactive book!)

[Some cells have been adapted from [Dr Eric Kerfoot's](https://kclpure.kcl.ac.uk/portal/eric.kerfoot.html)]